version: '3.1'

services:

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    volumes:
      - ./dist/my-app:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"

    networks:
      - app-network


networks:
  app-network:
    driver: bridge